package de.worketplace.team06.server.db;

import java.util.*;

import de.worketplace.team06.shared.bo.Project;

/**
 * 
 */
public class ProjectMapper {

	private static ProjectMapper projectMapper = null;
	 /**
	   * Gesch�tzter Konstruktor - verhindert die M�glichkeit, mit <code>new</code>
	   * neue Instanzen dieser Klasse zu erzeugen.
	   */
	protected ProjectMapper(){
		
	}
	
	public static ProjectMapper projecteMapper(){
		if (projectMapper == null){
			projectMapper = new ProjectMapper();
		}
		return projectMapper; 
	}

    /**
     * @param project 
     * @return
     */
    public Project insert(Project project) {
        // TODO implement here
        return null;
    }

    /**
     * @param project 
     * @return
     */
    public Project update(Project project) {
        // TODO implement here
        return null;
    }

    /**
     * @param project
     */
    public void delete(Project project) {
        // TODO implement here
    }

    /**
     * @return
     */
    public Vector<Project> findAll() {
        // TODO implement here
        return null;
    }
    
    //Auto generated by Johannes 
	public Vector<Project> findByMarketplaceID(int id) {
		// TODO Auto-generated method stub
		return null;
	}
	
    //Auto generated by Johannes
	public Project findByID(int projectID) {
		// TODO Auto-generated method stub
		return null;
	}
	
	//Auto generated by Johannes
	public Vector<Project> findByProjectOwnerID(int id) {
		// TODO Auto-generated method stub
		return null;
	}

	//Auto generated by Johannes
	public Vector<Project> findByProjectLeaderID(int id) {
		// TODO Auto-generated method stub
		return null;
	}

	
}
