package de.worketplace.team06.server.db;

import java.util.*;

import de.worketplace.team06.shared.bo.Property;

/**
 * 
 */
public class PropertyMapper {

	private static PropertyMapper propertyMapper = null;
	 /**
	   * Gesch�tzter Konstruktor - verhindert die M�glichkeit, mit <code>new</code>
	   * neue Instanzen dieser Klasse zu erzeugen.
	   */
	protected PropertyMapper(){
		
	}
	
	public static PropertyMapper propertyMapper(){
		if (propertyMapper == null){
			propertyMapper = new PropertyMapper();
		}
		return propertyMapper; 
	}

    /**
     * @param property 
     * @return
     */
    public Property insert(Property property) {
        // TODO implement here
        return null;
    }

    /**
     * @param property 
     * @return
     */
    public Property update(Property property) {
        // TODO implement here
        return null;
    }

    /**
     * @param property 
     * @return
     */
    public Property delete(Property property) {
        // TODO implement here
        return null;
    }

  //AutoGeneratedBy Johannes
	public Vector<Property> findByPartnerProfileID(int id) {
		// TODO Auto-generated method stub
		return null;
	}

	
}
